BEDUremote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: <p align="center"> Pierre BEDU </p>
description: <link href="description.html" rel="import" />

email: pierrebedu@yahoo.fr
show_downloads: "false"
